os: linux

# see https://medium.com/@bezgachev/6-simple-steps-to-automatically-test-and-deploy-your-javascript-app-to-github-pages-c4c32a34bcb1
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t carmemias/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carmemias/docker-react yarn test

# deploy:
  # edge: true
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY
  # provider: elasticbeanstalk
  # region: "us-west-2"
  # app: "docker-react"
  # env: "Docker-env"
  # bucket_name: ... (the AWS S3 bucket name)
  # bucket_path: "docker-react" (the AWS S3 bucket path)
  # on:
  #   branch: master (only deploy when there are changes to the master branch)
